/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.beyondb.ui;

import com.beyondb.datasource.DataSource;
import com.beyondb.utils.HttpRequestUtl;
import com.beyondb.utils.OpenURLUtil;
import com.beyondb.utils.initSystemParams;
import java.awt.Desktop;
import java.awt.GridLayout;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lbs
 */
public class DataEditor extends javax.swing.JFrame implements  IDialog{
    private final JPanel_DataBaseTables m_ShowDataBaseTablesPanel;

    /**
     * Creates new form DataEditor
     */
    public DataEditor() {
        initComponents();
        m_ShowDataBaseTablesPanel = new JPanel_DataBaseTables(this);
        jPanel_DBtbls.add(m_ShowDataBaseTablesPanel);
        jPanel_DBtbls.setLayout(new GridLayout(1, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_DBtbls = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton_sendGet = new javax.swing.JButton();
        jTextField_getRequest = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_postRequest = new javax.swing.JTextField();
        jButton_sendPost = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("数据编辑工具");

        javax.swing.GroupLayout jPanel_DBtblsLayout = new javax.swing.GroupLayout(jPanel_DBtbls);
        jPanel_DBtbls.setLayout(jPanel_DBtblsLayout);
        jPanel_DBtblsLayout.setHorizontalGroup(
            jPanel_DBtblsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        jPanel_DBtblsLayout.setVerticalGroup(
            jPanel_DBtblsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("读取数据库信息");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton_sendGet.setText("确定");
        jButton_sendGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sendGetActionPerformed(evt);
            }
        });

        jLabel2.setText("post请求");

        jButton_sendPost.setText("发送post请求");
        jButton_sendPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sendPostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_DBtbls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton1)
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_postRequest))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_getRequest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_sendGet, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_sendPost)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_DBtbls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_getRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_sendGet))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_postRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_sendPost)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //暂时读取信息
        DataSource ds = m_ShowDataBaseTablesPanel.getDataSource();
        String tableName= m_ShowDataBaseTablesPanel.getTableNameFromTree();
        String info ="";
        if (ds==null) {
            return;
        }
        info +="数据库名称:          "+ds.getDatabaseName()+"\n";
        info +="数据库驱动:          "+ds.getDriver()+"\n";
        info +="数据库所有主机IP:     "+ds.getIp()+"\n";
        info +="用户名:               "+ds.getName()+"\n";
        info +="密码:                 "+ds.getPassword()+"\n";
        info +="连接字符串:            "+ds.getUrl()+"\n";
        info +="当前选中的表:          "+tableName+"\n";
        info+="-----------------------------------------------"+"\n";
        info +="数据编辑工具服务器地址:"+initSystemParams.getInstance().getSystemParam(initSystemParams.PARAM.PARAM_DATAEDIT_TOOL_URL);
        jTextArea1.setText(info);
       
        String dataEdit_Url = String.valueOf(initSystemParams.getInstance().getSystemParam(initSystemParams.PARAM.PARAM_DATAEDIT_TOOL_URL));
        String url_post = "";
        String port = "";
        //如果有http://协议头，删除
        dataEdit_Url = dataEdit_Url.toLowerCase().replace("http://", "");
        //如果有端口号
        if (dataEdit_Url.contains(":")) {
            String[] array=dataEdit_Url.split(":");
            dataEdit_Url=array[0];
            port = array[1];
        } else {
            port = "8080";
        }
         String url_Base_post = "http://%s:%s/poiqueryservice/getpoitns?dbname=%s";
         url_post = String.format(url_Base_post,dataEdit_Url,port,ds.getDatabaseName());
         jTextField_postRequest.setText(url_post);
         
        String url_Base_get = "http://%s:%s/poiqueryservice/getpoitns?vusername=%s&vpw=%s&vurl=%s&dbname=%s";
        
        String url_get = String.format(url_Base_get,
                dataEdit_Url, port,
                ds.getName(), ds.getPassword(), ds.getUrl(),
                ds.getDatabaseName());
        jTextField_getRequest.setText(url_get);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_sendPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sendPostActionPerformed
        // TODO add your handling code here:
        DataSource ds = m_ShowDataBaseTablesPanel.getDataSource();
        generatehttpPostRequest(ds);
    }//GEN-LAST:event_jButton_sendPostActionPerformed

    private void jButton_sendGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sendGetActionPerformed
        // TODO add your handling code here:
          String url=jTextField_getRequest.getText();
        if (url.isEmpty()) {
            return;
        }
 
        //打开web浏览器
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().browse(new URI(url));
            }else
            {
                OpenURLUtil.openURL(url);
            }
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(DataEditor.class.getName()).log(Level.SEVERE, "打开数据编辑工具网址出错", ex);
        }

          
    }//GEN-LAST:event_jButton_sendGetActionPerformed


    private void generatehttpPostRequest(DataSource ds)
    {
//         URL为  http://IP地址:8080/poiediter/poiqueryservice/getpoitns?dbname=数据库名称
//  http体部需要参数vusername=用户名
//                  vpw=密码
//                  vurl=连接串
        String url=jTextField_postRequest.getText();
        if (url.isEmpty()) {
            return;
        }
        String param_Base ="vusername=%s&vpw=%s&vurl=%s";
         String param =String.format(param_Base, ds.getName(),ds.getPassword(),ds.getUrl());
            //发送 POST 请求
        String sr=HttpRequestUtl.sendPost(url, param);
        System.out.println(sr);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_sendGet;
    private javax.swing.JButton jButton_sendPost;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel_DBtbls;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_getRequest;
    private javax.swing.JTextField jTextField_postRequest;
    // End of variables declaration//GEN-END:variables

    /**
     * 弹出对话框
     *
     * @param msg 内容
     * @param JOptionPanestyle 样式
     */
    @Override
    public void setShowMessage(String msg, int JOptionPanestyle) {

        JOptionPane.showMessageDialog(this, msg, "提示", JOptionPanestyle);
    }

    @Override
    public int setShowConfirmDialog(String msg) {
        return JOptionPane.showConfirmDialog(this, msg, "确认", JOptionPane.YES_NO_OPTION);
    }
        /**
     *
     * @param panel 面板
     * @param title  标题
     * @param JOptionPanestyle 样式
     * @return
     */
    @Override
    public int setShowConfirmDialog(JPanel panel,String title,int JOptionPanestyle) {
        return JOptionPane.showConfirmDialog(this,panel, title,JOptionPanestyle,JOptionPane.PLAIN_MESSAGE);
           
    }
}
